### ISSUE TITLE
Update version of Elixir + Erlang/OTP in elixir_buildpack.config

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-heroku#40]
At present, the instructions in our Elixir/Phoenix Deployment guide instruct people to use Elixir `1.6`
[elixir-phoenix-app-deployment.md#5-create-a-elixir_buildpackconfig-file](https://github.com/dwyl/learn-heroku/blob/8a6f11d97c7abe88238384824fb3602bca1cfc98/elixir-phoenix-app-deployment.md#5-create-a-elixir_buildpackconfig-file)

![image](https://user-images.githubusercontent.com/194400/71085689-002a4980-2190-11ea-9526-f36102c13b09.png)

While this version is perfectly fine, it's a couple of years old and should not be used for ***`NEW`*** apps.

I recently used the _latest_ Elixir + Erlang in [dwyl/elixir-auth-google-demo > elixir_buildpack.config](https://github.com/dwyl/elixir-auth-google-demo/blob/d1a42e3855b63ba5719737cd4c533131b7add9ae/elixir_buildpack.config#L2)
Which is working on: https://elixir-auth-google-demo.herokuapp.com 
So I am confident that updating the instructions will not cause any beginners to have headaches.

# Todo

+ [x] Update instructions for `elixir_buildpack.config` to Elixir `v1.9.4` 
  + [x]  for latest version see: https://github.com/elixir-lang/elixir/releases
+ [x] Update version of Erlang to `22.2`
  + [x] For latest available version of OTP for Heroku, 
see: https://github.com/HashNuke/heroku-buildpack-elixir-otp-builds/blob/master/otp-versions

**Comment by nelsonic** [comment]
@iteles please see PR: #41 
Thanks! 🌻
